// src/ui/svelte/lib/MovieView.svelte
<script lang="ts">
  import type { Movie } from '../../../entities/movie'
  import { POSTER_BASE_URL } from '../../../entities/themoviedb'
  export let movie: Movie
</script>

<div>
  <h2>{movie.title}</h2>
  <img
    src={`${POSTER_BASE_URL}${movie.poster_path}`}
    width="500px"
    height="500px"
    alt={movie.title}
  />
  <p>{movie.overview}</p>
</div>

// src/ui/vue/components/MovieView.vue
<script setup lang="ts">
import { POSTER_BASE_URL } from '../../../entities/themoviedb'

const props = defineProps({
  movie: {
    type: Object
  }
})
</script>


<template>
  <h2>{{ props.movie.title }}</h2>
  <img :src="`${POSTER_BASE_URL}${props.movie.poster_path}`" width="500" height="500" :alt="props.movie.title" />
  <p>{{ props.movie.overview }}</p>
  <p>{{ props.movie.vote_average }}</p>
</template>
