// src/ui/react/App.tsx
import { useEffect, useState } from 'react'
import { discoverMovies } from '../../controller/themoviedb'
import type { Movie } from '../../entities/movie'
import MovieView from './components/MovieView'

const initialMovies: Movie[] = []
function App() {
  const [movies, setMovies] = useState(initialMovies)

  useEffect(() => {
    discoverMovies((xs) => setMovies(xs))
  }, [])
  return (
    <div className="App">
      <main>
        <h1>Movies</h1>
        <div>
          {movies.map((movie) => (
            <MovieView key={movie.title} movie={movie} />
          ))}
        </div>
      </main>
    </div>
  )
}

export default App

// src/ui/vue/App.vue
<script setup lang="ts">
import type { Movie } from '../../entities/movie'
import MovieView from './components/MovieView.vue'
import { discoverMovies } from '../../controller/themoviedb'
import { onMounted } from 'vue'

import { reactive } from 'vue'

const initialMovies: Movie[] = []

const store = reactive({
  movies: initialMovies
})

onMounted(() => {
  discoverMovies((xs) => {
    store.movies = xs
  })
})
</script>

<template>
  <h1>Movies</h1>

  <div v-for="movie in store.movies">
    <MovieView :movie="movie" />
  </div>
</template>
